language: java
sudo: true
# Can't update to xenial distribution (ubuntu 16.04) bause of the Java JDK restriction (Not supporting )
dist: trusty

# Using -q Quiet output which only show errors, to overcome TravisCI log limit issue
script: mvn clean install -Dmaven.test.skip -q -B -V | grep -v DEBUG; exit "${PIPESTATUS[0]}";

cache:
  directories:
  - $HOME/.m2_1
  - $HOME/.m2
  - features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/node_modules
  - features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/node_modules
